#!/bin/bash

echo "show tables like 'chipau%'" | \
mysql -N -u user -p'' db | \
sed '/^.\+$/!d'                       | \
sed 's/.\+/`&`/'                      | \
sed ':a;N;$!ba;s/\n/,/g'              | \
sed 's/^.\+/DROP TABLE IF EXISTS &;/' | \
mysql -u user -p'' db
